env:

language: rust

install:
	
  - sudo apt-get install libgtk-3-dev
  # Build and install from source lib iup
  # make in iup exit code is 2 even if it builds the needed library ./lib/libiup.so
  # executing an echo will continue the next lines of the builds in travi-ci
  - git clone https://github.com/ivanceras/iup-mirror
  - cd iup-mirror && make || ( echo "continue even if make fails" )
  # By piping a newline to ./install, we skip the enter prompt
  - echo -ne '\n' | sudo ./install
  - rm -rf ./lib

script:
  - cargo build -v
  - cargo test -v
